### ISSUE TITLE
Platform error device_tracker.whistle

### ISSUE THREAD

**Issue by UndarkAido** [Fusion/pywhistle#4]
When I try to validate my configuration I get
```
Platform error device_tracker.whistle - Integration 'whistle' not found.
Invalid config for [sensor]: required key not provided @ data['platform']. Got None. (See /config/configuration.yaml, line 21).
```

`device_tracker.py` and the adjacent files are in `~/config/custom_components/whistle`

I installed all of the `pip` packages required for `device_tracker.py` to not complain when I run it for the command line. Maybe that wasn't needed?

I added this to my `configuration.yaml`:
```yaml
device_tracker:
  - platform: whistle
    username: !secret whistle_username
    password: !secret whistle_password
    monitored_variables:
      - WHISTLE
```

What am I missing?
