### ISSUE TITLE
Platform error device_tracker.whistle - Integration 'whistle' not found.

### ISSUE THREAD

**Issue by jrobbs123** [Fusion/pywhistle#8]
I have tried the newest steps to install and a few other ways but just keep getting this error.
"Platform error device_tracker.whistle - Integration 'whistle' not found."  i rebooted, removed and re-installed, moved files around, ...

i am running 
Host
Operating System
Home Assistant OS 6.0
--
Supervisor
Version
supervisor-2021.06.6
Newest Version
supervisor-2021.06.6
--
Core
Version
core-2021.6.6
Newest Version
core-2021.6.6

I also created a folder under the custom_components and cp all the files that were in the examples/homeassistant folder.  still same error.  

custom_components $ ls
alexa_media  emporia_vue  govee        hacs         pywhistle    scheduler    whistle
custom_components $
custom_components $ cd whistle/
whistle $ ls
README.md          __init__.py        device_tracker.py  manifest.json
whistle $ ls -al
total 24
drwxr-xr-x    2 root     root          4096 Jul  3 13:45 .
drwxr-xr-x    9 root     root          4096 Jul  3 13:42 ..
-rw-r--r--    1 root     root          3086 Jul  3 13:44 README.md
-rw-r--r--    1 root     root            31 Jul  3 13:45 __init__.py
-rw-r--r--    1 root     root          3478 Jul  3 13:45 device_tracker.py
-rw-r--r--    1 root     root           292 Jul  3 13:45 manifest.json
whistle $

one thing to note, i already have the life360 integration installed (not custom) and noticed that also falls under device_tracker. it is not in the configuration.yaml file but must be listed somewhere.  Would this cause the issue if HA already has device_tracker defined for a supported integration? ??

just looking for any help.  would love to have this working but tried as many things as i can think of.

thx

**Comment by Fusion** [comment]
This is a bit crazy.

Of course you can have multiple device tracker integrations. And your setup looks correct!

Running HA 2021.6.6, here is what I have:

`configuration.yaml`:

```
device_tracker:
  - platform: tile
    username: !secret tile_username
    password: !secret tile_password
    monitored_variables:
      - TILE
  - platform: whistle
    username: !secret whistle_username
    password: !secret whistle_password
    monitored_variables:
      - WHISTLE
  - platform: nmap_tracker
    hosts: 192.168.1.0/24
```

and indeed:

```
ls custom_components/whistle/
__init__.py  __pycache__  device_tracker.py  manifest.json
```
